/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetGUI;

import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import classes.DAO.CoursDAO;
import classes.metiers.Cours;

/**
 *
 * @author jeanl
 */
public class AffCours extends javax.swing.JPanel {

    CoursDAO coursDAO = null;
    DefaultTableModel dft1 = new DefaultTableModel();

    /**
     * Creates new form AffCours
     */
    public AffCours() {
        initComponents();

        dft1.addColumn("Id cours");
        dft1.addColumn("Matière");
        dft1.addColumn("Nombre d'heures");
        tbl_rech.setModel(dft1);

    }

    public void setCoursDAO(CoursDAO coursDAO) {
        this.coursDAO = coursDAO;
    }

    /*public void setLocationDAO(LocationDAO locationDAO) {
        this.locationDAO = locationDAO;
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_titre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_rech = new javax.swing.JTable();
        textLoc = new javax.swing.JTextField();
        lbl_imma = new javax.swing.JLabel();

        lbl_titre.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lbl_titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titre.setText("Affichage des cours");

        tbl_rech.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_rech);

        textLoc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        textLoc.setMinimumSize(new java.awt.Dimension(50, 20));
        textLoc.setPreferredSize(new java.awt.Dimension(150, 30));
        textLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textLocActionPerformed(evt);
            }
        });

        lbl_imma.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_imma.setText("Cours recherché :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_titre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(lbl_imma)
                .addGap(18, 18, 18)
                .addComponent(textLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl_titre, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_imma)
                    .addComponent(textLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textLocActionPerformed
        try {
            if (!textLoc.getText().isEmpty()) {
                String loc = textLoc.getText();
                System.out.println(loc);
                List<Cours> cours = coursDAO.rechNom(loc);
                
                int nr = dft1.getRowCount();
                for (int i = nr - 1; i >= 0; i--) {
                    dft1.removeRow(i);
                }
                
                for (Cours l1 : cours) {
                    Vector v = new Vector();
          
                    v.add(l1.getIdcours());
                    v.add(l1.getMatière());
                    v.add(l1.getHeures());
                    System.out.println(cours);

                    dft1.addRow(v);

                }

            } else {
                JOptionPane.showMessageDialog(this, "Le champ est vide, veuillez le compléter", "ERREUR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Aucun cours correspondant", "ERREUR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_textLocActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_imma;
    private javax.swing.JLabel lbl_titre;
    private javax.swing.JTable tbl_rech;
    private javax.swing.JTextField textLoc;
    // End of variables declaration//GEN-END:variables
}
