/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetGUI;

import classes.DAO.CoursDAO;
import classes.DAO.FormateurDAO;
import classes.DAO.InfoDAO;
import classes.DAO.LocalDAO;
import classes.DAO.SessionDAO;
import java.awt.CardLayout;
import java.sql.Connection;
import javax.swing.JOptionPane;
import myconnections.DBConnection;

/**
 *
 * @author jeanl
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form frame
     */
    CardLayout cardl;
    public Frame() {
        initComponents();
        cardl=(CardLayout)this.getContentPane().getLayout();
        cardl.show(this.getContentPane(), "card2");
        Connection dbConnect = DBConnection.getConnection();
        if (dbConnect == null) {
            System.out.println("connection invalide");
            JOptionPane.showMessageDialog(this,"connexion invalide","ERREUR",JOptionPane.ERROR_MESSAGE);
        }
        
        LocalDAO localDAO = new LocalDAO();
        localDAO.setConnection(dbConnect);
        CoursDAO coursDAO = new CoursDAO();
        coursDAO.setConnection(dbConnect);
        FormateurDAO formateurDAO = new FormateurDAO();
        formateurDAO.setConnection(dbConnect);
        SessionDAO sessionDAO = new SessionDAO();
        sessionDAO.setConnection(dbConnect);
        InfoDAO infoDAO = new InfoDAO();
        infoDAO.setConnection(dbConnect);
        
        localGUI1.setLocalDAO(localDAO);
        affLocal1.setLocalDAO(localDAO);
        affCours1.setCoursDAO(coursDAO);
        affForm2.setFormateurDAO(formateurDAO);
        coursGUI1.setCoursDAO(coursDAO);
        formateurGUI1.setFormateurDAO(formateurDAO);
        affSess1.setSessionDAO(sessionDAO);
        sessionGUI1.setSessionDAO(sessionDAO);
        sessionGUI1.setInfoDAO(infoDAO);
                
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        coursGUI1 = new projetGUI.CoursGUI();
        formateurGUI1 = new projetGUI.FormateurGUI();
        localGUI1 = new projetGUI.LocalGUI();
        mainMenu2 = new projetGUI.MainMenu();
        affLocal1 = new projetGUI.AffLocal();
        affCours1 = new projetGUI.AffCours();
        affForm2 = new projetGUI.AffForm();
        affSess1 = new projetGUI.AffSess();
        sessionGUI1 = new projetGUI.SessionGUI();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        buttHome = new javax.swing.JMenuItem();
        buttQuit = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        Session = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new java.awt.CardLayout());
        getContentPane().add(coursGUI1, "card3");
        getContentPane().add(formateurGUI1, "card4");
        getContentPane().add(localGUI1, "card5");
        getContentPane().add(mainMenu2, "card2");
        getContentPane().add(affLocal1, "card11");
        getContentPane().add(affCours1, "card13");
        getContentPane().add(affForm2, "card14");
        getContentPane().add(affSess1, "card9");
        getContentPane().add(sessionGUI1, "card10");

        jMenu4.setText("Menu");

        buttHome.setText("Home");
        buttHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttHomeActionPerformed(evt);
            }
        });
        jMenu4.add(buttHome);

        buttQuit.setText("Quitter");
        buttQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttQuitActionPerformed(evt);
            }
        });
        jMenu4.add(buttQuit);

        jMenuBar1.add(jMenu4);

        jMenu6.setText("Affichage");

        jMenuItem9.setText("Cours");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem9);

        jMenuItem8.setText("Local");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem8);

        jMenuItem10.setText("Formateur");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem10);

        jMenuItem5.setText("Session");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem5);

        jMenuBar1.add(jMenu6);

        jMenu5.setText("Accès");

        jMenuItem1.setText("Cours");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuItem2.setText("Local");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuItem4.setText("Formateur");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem4);

        Session.setText("Session");
        Session.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SessionActionPerformed(evt);
            }
        });
        jMenu5.add(Session);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttQuitActionPerformed

    private void buttHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttHomeActionPerformed
        cardl.show(this.getContentPane(), "card2");
    }//GEN-LAST:event_buttHomeActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        cardl.show(this.getContentPane(), "card4");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        cardl.show(this.getContentPane(), "card3");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        cardl.show(this.getContentPane(), "card5");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        cardl.show(this.getContentPane(), "card11");
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        cardl.show(this.getContentPane(), "card13");
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        cardl.show(this.getContentPane(), "card14");
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        cardl.show(this.getContentPane(), "card9");
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void SessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SessionActionPerformed
        cardl.show(this.getContentPane(), "card10");
    }//GEN-LAST:event_SessionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Session;
    private projetGUI.AffCours affCours1;
    private projetGUI.AffForm affForm2;
    private projetGUI.AffLocal affLocal1;
    private projetGUI.AffSess affSess1;
    private javax.swing.JMenuItem buttHome;
    private javax.swing.JMenuItem buttQuit;
    private projetGUI.CoursGUI coursGUI1;
    private projetGUI.FormateurGUI formateurGUI1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private projetGUI.LocalGUI localGUI1;
    private projetGUI.MainMenu mainMenu2;
    private projetGUI.SessionGUI sessionGUI1;
    // End of variables declaration//GEN-END:variables
}
