/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projetGUI;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import classes.DAO.LocalDAO;
import classes.metiers.Local;

/**
 *
 * @author jeanl
 */
public class GesForm extends javax.swing.JPanel {
    
    LocalDAO localDAO = null;
    Local loc1 = null;

    /** Creates new form GesLocal */
    public GesForm() {
        initComponents();
    }
    
    public void setLocalDAO(LocalDAO localDAO) {
        this.localDAO = localDAO;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textPLACES = new javax.swing.JTextField();
        textDESC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbl_kmtotaux = new javax.swing.JLabel();
        lbl_acompte = new javax.swing.JLabel();
        lbl_id_loc = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        textIDLOC = new javax.swing.JTextField();
        textSIGLE = new javax.swing.JTextField();
        buttRech = new javax.swing.JButton();
        buttUpdate = new javax.swing.JButton();
        buttDel = new javax.swing.JButton();

        textPLACES.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        textPLACES.setMinimumSize(new java.awt.Dimension(50, 20));
        textPLACES.setPreferredSize(new java.awt.Dimension(150, 30));
        textPLACES.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textPLACESKeyTyped(evt);
            }
        });

        textDESC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        textDESC.setMinimumSize(new java.awt.Dimension(50, 20));
        textDESC.setPreferredSize(new java.awt.Dimension(150, 30));
        textDESC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textDESCKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestion d'un local via identifiant");

        lbl_kmtotaux.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_kmtotaux.setText("Sigle :");

        lbl_acompte.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_acompte.setText("Places :");

        lbl_id_loc.setText("ID du local :");

        lbl_total.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_total.setText("Description :");

        textIDLOC.setMinimumSize(new java.awt.Dimension(50, 20));
        textIDLOC.setPreferredSize(new java.awt.Dimension(150, 30));
        textIDLOC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIDLOCActionPerformed(evt);
            }
        });
        textIDLOC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textIDLOCKeyTyped(evt);
            }
        });

        textSIGLE.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        textSIGLE.setMinimumSize(new java.awt.Dimension(50, 20));
        textSIGLE.setPreferredSize(new java.awt.Dimension(150, 30));
        textSIGLE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textSIGLEKeyTyped(evt);
            }
        });

        buttRech.setText("Rechercher le local");
        buttRech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttRechActionPerformed(evt);
            }
        });

        buttUpdate.setText("Update le local");
        buttUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttUpdateActionPerformed(evt);
            }
        });

        buttDel.setText("Delete le local");
        buttDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_id_loc)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_kmtotaux, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_acompte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_total, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textSIGLE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(textPLACES, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textDESC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(textIDLOC, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(buttRech)
                        .addGap(18, 18, 18)
                        .addComponent(buttUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(buttDel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_id_loc)
                    .addComponent(textIDLOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSIGLE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_kmtotaux))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_acompte)
                    .addComponent(textPLACES, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textDESC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttRech, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttDel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textIDLOCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIDLOCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIDLOCActionPerformed

    private void buttRechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttRechActionPerformed

        try {
            if (!textIDLOC.getText().isEmpty()) {
                int idLoc = Integer.parseInt(textIDLOC.getText());
                loc1 = localDAO.read(idLoc);
                textSIGLE.setText(""+loc1.getSigle());
                textPLACES.setText(""+loc1.getPlaces());
                textDESC.setText(""+loc1.getDescription());
               
                JOptionPane.showMessageDialog(this, "Local trouvé", "Found", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Champ d'ID vide, veuillez le compléter", "ERREUR", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERREUR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttRechActionPerformed

    private void buttUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttUpdateActionPerformed
        try {
            if (!textIDLOC.getText().isEmpty()) {
                int idLoc=Integer.parseInt(textIDLOC.getText());
                String sigle = textSIGLE.getText();
                int places = Integer.parseInt(textPLACES.getText());
                String desc = textDESC.getText();
                Local loc1 = new Local(idLoc,sigle,places,desc);
                localDAO.update(loc1);
                JOptionPane.showMessageDialog(this, "Local mis à jour", "success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Champ d'ID vide, veuillez le compléter", "ERREUR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERREUR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttUpdateActionPerformed

    private void buttDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttDelActionPerformed
        try {
            if (!textIDLOC.getText().isEmpty()) {
                int id_loc = Integer.parseInt(textIDLOC.getText());
                localDAO.delete(loc1);
                textPLACES.setText("");
                textIDLOC.setText("");
                textSIGLE.setText("");
                textDESC.setText("");
                JOptionPane.showMessageDialog(this, "Local effacé", "success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Champ d'ID vide, veuillez le compléter", "ERREUR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERREUR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttDelActionPerformed

    private void textIDLOCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textIDLOCKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c) || (Character.isSpaceChar(c))) {
            textIDLOC.setEditable(false);
        } else {
            textIDLOC.setEditable(true);
        }
    }//GEN-LAST:event_textIDLOCKeyTyped

    private void textSIGLEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textSIGLEKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c) || (Character.isSpaceChar(c))) {
            textSIGLE.setEditable(false);
        } else {
            textSIGLE.setEditable(true);
        }
    }//GEN-LAST:event_textSIGLEKeyTyped

    private void textPLACESKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPLACESKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c) || (Character.isSpaceChar(c))) {
            textPLACES.setEditable(false);
        } else {
            textPLACES.setEditable(true);
        }
    }//GEN-LAST:event_textPLACESKeyTyped

    private void textDESCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textDESCKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c) || (Character.isSpaceChar(c))) {
            textDESC.setEditable(false);
        } else {
            textDESC.setEditable(true);
        }
    }//GEN-LAST:event_textDESCKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttDel;
    private javax.swing.JButton buttRech;
    private javax.swing.JButton buttUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_acompte;
    private javax.swing.JLabel lbl_id_loc;
    private javax.swing.JLabel lbl_kmtotaux;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JTextField textDESC;
    private javax.swing.JTextField textIDLOC;
    private javax.swing.JTextField textPLACES;
    private javax.swing.JTextField textSIGLE;
    // End of variables declaration//GEN-END:variables

}
